name: Test against supported Java versions

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '8', '11', '17', '20', '21-ea' ]
    name:  Test against Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout tls-gen
        uses: actions/checkout@v3
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
      - name: Display Java version
        run: ./mvnw --version
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Dca.certificate=./tls-gen/basic/result/ca_certificate.pem \
            -Dclient.certificate=./tls-gen/basic/result/client_$(hostname)_certificate.pem \
            -Dclient.key=./tls-gen/basic/result/client_$(hostname)_key.pem \
            -Dnet.bytebuddy.experimental=true
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
